# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deliv.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 591)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(11, 11, 631, 261))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.txtNum = QtWidgets.QLineEdit(self.splitter)
        self.txtNum.setObjectName("txtNum")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rdHan = QtWidgets.QRadioButton(self.widget)
        self.rdHan.setObjectName("rdHan")
        self.horizontalLayout.addWidget(self.rdHan)
        self.rdCJ = QtWidgets.QRadioButton(self.widget)
        self.rdCJ.setObjectName("rdCJ")
        self.horizontalLayout.addWidget(self.rdCJ)
        self.rdUck = QtWidgets.QRadioButton(self.widget)
        self.rdUck.setObjectName("rdUck")
        self.horizontalLayout.addWidget(self.rdUck)
        self.rdLot = QtWidgets.QRadioButton(self.widget)
        self.rdLot.setObjectName("rdLot")
        self.horizontalLayout.addWidget(self.rdLot)
        self.rdLog = QtWidgets.QRadioButton(self.widget)
        self.rdLog.setObjectName("rdLog")
        self.horizontalLayout.addWidget(self.rdLog)
        self.rdDhl = QtWidgets.QRadioButton(self.widget)
        self.rdDhl.setObjectName("rdDhl")
        self.horizontalLayout.addWidget(self.rdDhl)
        self.rdUps = QtWidgets.QRadioButton(self.widget)
        self.rdUps.setObjectName("rdUps")
        self.horizontalLayout.addWidget(self.rdUps)
        self.rdFedex = QtWidgets.QRadioButton(self.widget)
        self.rdFedex.setObjectName("rdFedex")
        self.horizontalLayout.addWidget(self.rdFedex)
        self.btnSearch = QtWidgets.QPushButton(self.splitter)
        self.btnSearch.setObjectName("btnSearch")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "택배 배송조회"))
        self.label.setText(_translate("MainWindow", "송장번호를 입력하세요"))
        self.label_2.setText(_translate("MainWindow", "조회할 택배사를 선택하세요"))
        self.rdHan.setText(_translate("MainWindow", "한진택배"))
        self.rdCJ.setText(_translate("MainWindow", "CJ대한통운"))
        self.rdUck.setText(_translate("MainWindow", "우체국택배"))
        self.rdLot.setText(_translate("MainWindow", "롯데택배"))
        self.rdLog.setText(_translate("MainWindow", "로젠택배"))
        self.rdDhl.setText(_translate("MainWindow", "DHL"))
        self.rdUps.setText(_translate("MainWindow", "UPS"))
        self.rdFedex.setText(_translate("MainWindow", "FEDEX"))
        self.btnSearch.setText(_translate("MainWindow", "조회하세요"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
