# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scrap_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 10, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.url = QtWidgets.QLineEdit(self.centralwidget)
        self.url.setGeometry(QtCore.QRect(10, 60, 571, 31))
        self.url.setObjectName("url")
        self.rb_10min = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_10min.setGeometry(QtCore.QRect(10, 140, 90, 16))
        self.rb_10min.setObjectName("rb_10min")
        self.rb_5min = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_5min.setGeometry(QtCore.QRect(110, 140, 90, 16))
        self.rb_5min.setObjectName("rb_5min")
        self.rb_3min = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_3min.setGeometry(QtCore.QRect(210, 140, 90, 16))
        self.rb_3min.setObjectName("rb_3min")
        self.rb_1min = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_1min.setGeometry(QtCore.QRect(310, 140, 90, 16))
        self.rb_1min.setObjectName("rb_1min")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 101, 16))
        self.label_2.setObjectName("label_2")
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(390, 120, 141, 61))
        self.btn_start.setObjectName("btn_start")
        self.btn_end = QtWidgets.QPushButton(self.centralwidget)
        self.btn_end.setGeometry(QtCore.QRect(540, 120, 141, 61))
        self.btn_end.setObjectName("btn_end")
        self.lbl_print = QtWidgets.QLabel(self.centralwidget)
        self.lbl_print.setGeometry(QtCore.QRect(30, 200, 661, 61))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_print.setFont(font)
        self.lbl_print.setText("")
        self.lbl_print.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_print.setObjectName("lbl_print")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.rb_10min.clicked.connect(MainWindow.setCycle)
        self.rb_5min.clicked.connect(MainWindow.setCycle)
        self.rb_3min.clicked.connect(MainWindow.setCycle)
        self.rb_1min.clicked.connect(MainWindow.setCycle)
        self.btn_start.clicked.connect(MainWindow.startChk)
        self.btn_end.clicked.connect(MainWindow.stopChk)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NCS/EMG"))
        self.label.setText(_translate("MainWindow", "주소입력"))
        self.rb_10min.setText(_translate("MainWindow", "10min"))
        self.rb_5min.setText(_translate("MainWindow", "5min"))
        self.rb_3min.setText(_translate("MainWindow", "3min"))
        self.rb_1min.setText(_translate("MainWindow", "1min"))
        self.label_2.setText(_translate("MainWindow", "주기를 선택하세요"))
        self.btn_start.setText(_translate("MainWindow", "체크시작"))
        self.btn_end.setText(_translate("MainWindow", "체크종료"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
